### ISSUE TITLE
Release Julia package to Julia package repository

### ISSUE THREAD

**Issue by ykharkov** [amazon-braket/BraketAHS.jl#4]
- Rename package to comply with Julia naming guidlines
- Add tests
- Add Documenter.jl

**Comment by virajvchaudhari** [comment]
Thank you for this issue! We will look into this.

**Comment by ykharkov** [comment]
@JuliaRegistrator register

**Comment by ykharkov** [comment]
@JuliaRegistrator register()

**Comment by ykharkov** [comment]
@JuliaRegistrator register()

**Comment by ykharkov** [comment]
@JuliaRegistrator register()

**Comment by ykharkov** [comment]
@JuliaRegistrator register()

**Comment by ykharkov** [comment]
@JuliaRegistrator register()

**Comment by ykharkov** [comment]
@JuliaRegistrator register()

**Comment by ykharkov** [comment]
@JuliaRegistrator register()

**Comment by kshyatt-aws** [comment]
This can be closed, no?

**Comment by ykharkov** [comment]
> This can be closed, no?

Yes, closing this. For the new version I'll create a new issue.

**Comment by ykharkov** [comment]
Closing as the registration is completed
